---
version: '3.0'

services:
  gradle:
    image: 'gradle:4.3-jdk7-alpine'
    working_dir: '/home/gradle/project'
    entrypoint: gradle test
    volumes:
      - '.:/home/gradle/project'
    links:
      - 'mysql'
      - 'rabbitmq'
    depends_on:
      - 'mysql'
      - 'rabbitmq'
  mysql:
    image: 'mysql:5'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '15672:15672'
