---
version: '3.0'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'iddd_collaboration'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
